### PR TITLE
Properly initialize tree items

### LINKED ISSUE #368: test discovery fails since vscode updated today
the output logs test discovery and running of tests, and the status-bar shows the tests being run, but the .net test explorer view shows the "no tests found" - text and a toast saying 

> Cannot read properties of null (reading 'command')

appears whenever i try to refresh the test-explorer.

bilde

### PR DESCRIPTION
**Pull request by d-nery**
This should fix #368

See https://github.com/microsoft/vscode/issues/157273#issuecomment-1217572544 
And https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostTypes.ts#L2437

Instantiating the class bypasses some checks that made the exception be thrown

### CODE REVIEW

**Comment by d-nery** [comment]
Tested only on windows

```
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by TomasEkeli** [comment]
excellent work! 

i have tested this in windows and in linux on windows-subsystem-for linux and in linux running in a devcontainer. i can confirm that it works perfectly!

this pull-request has my vote!

**Comment by TomasEkeli** [comment]
until there's a proper release: https://github.com/TomasEkeli/vscode-dotnet-test-explorer/releases/tag/0.7.8-tomas-preview-1

**Comment by deitry** [comment]
Tested on Ubuntu 22.04, it works great. Thank you!

**Comment by NickReinlein** [comment]
Tested **successfully** on Linux Mint Cinnamon 20.3 (linux kernel 5.15.0), VSCode 1.71.0! 
Thank you!

**Comment by carlosxup** [comment]
Tested on MacOs Monterey 12.5.1, it works great!! 🔥

**Review by dittrichlucas — APPROVED** [review]

**Review by njevdjo — APPROVED** [review]
Tested on Windows, it works great. Thank you!
```
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
```

**Comment by JasonFoglia** [comment]
Tested successfully on Mac Monterey 12.6 (M1 Max).

**Comment by Sellebjergen** [comment]
Do we have a timeframe as to when this feature will be merged into master?

**Comment by janhurst** [comment]
Would also like to see this merged, my team is juggling this issue in a shared devcontainer and I really don't want to default to the flat list view.

**Comment by stefanforsberg** [comment]
Thanks a lot for this and sorry for slow merging. It's merged now and I'll contact Jun to get a proper release out.

**Comment by formulahendry** [comment]
New release is published: https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer
Thank you all!

**Pull request merged**
